## Cleaning Each Dataset

In [4]:
# install libraries
# %pip install pandas openpyxl numpy matplotlib seabor

import pandas as pd

In [6]:
costs = pd.read_excel("../data/raw/costs.xlsx")

In [7]:
gates = pd.read_excel("../data/raw/gates.xlsx")

In [8]:
transactions = pd.read_excel("../data/raw/transactions.xlsx")

## Costs

In [67]:
costs.head(10)

,Cost_ID,Cost_Date,Cost_Type,Route_ID,From,To,Amount
0,CO000001,2024-09-01 06:30:00,Crew,YVR-YLW,Vancouver,Kelowna,1388.53
1,CO000002,2024-09-01 06:30:00,Food,yvr-ylw,Vancouver,Kelowna,170.52
2,CO000003,2024-09-01 06:30:00,Fuel,YVR-YLW,Vancouver,Kelowna,1401.75
3,CO000004,2024-09-01 06:30:00,Maintenance,yvrylw,Vancouver,Kelowna,1657.45
4,CO000005,2024-09-01 06:35:00,Crew,YLW-YYC,Kelowna,Calgary,1673.28
5,CO000006,2024-09-01 06:35:00,Food,ylwyyc,Kelowna,Calgary,221.60
6,CO000007,2024-09-01 06:35:00,Fuel,YLW-YYC,Kelowna,Calgary,1800.44
7,CO000008,2024-09-01 06:35:00,Maintenance,YLW-YYC,Kelowna,Calgary,1898.61
8,CO000009,2024-09-01 06:45:00,Crew,YYZYYC,Toronto,Calgary,12105.73
9,CO000010,2024-09-01 06:45:00,Food,YYZYYC,Toronto,Calgary,2037.11

In [ ]:
# costs.info()
# costs.shape
# costs.isna().sum()
# costs.duplicated().sum()

,Cost_ID,Cost_Date,Cost_Type,Route_ID,From,To,Amount
0,CO000001,2024-09-01 06:30:00,Crew,YVR-YLW,Vancouver,Kelowna,1388.53
1,CO000002,2024-09-01 06:30:00,Food,yvr-ylw,Vancouver,Kelowna,170.52
2,CO000003,2024-09-01 06:30:00,Fuel,YVR-YLW,Vancouver,Kelowna,1401.75
3,CO000004,2024-09-01 06:30:00,Maintenance,yvrylw,Vancouver,Kelowna,1657.45
4,CO000005,2024-09-01 06:35:00,Crew,YLW-YYC,Kelowna,Calgary,1673.28

## Gates

In [66]:
gates.head(10)

         City Gate_Number Route_ID       Year  Annual_Gate_Cost
0  Abbotsford          G1  yxx-yyc  2024-2025            166800
1     Calgary          B1   YYCYVR  2024-2025            373200
2     Calgary          B1   yycyyz  2024-2025            373200
3     Calgary          B1   YYCYEG  2024-2025            373200
4     Calgary          B2  yyc-ywg  2024-2025            351900
5     Calgary          B2   YYCYXE  2024-2025            351900
6     Calgary          B2  YYC-YQR  2024-2025            351900
7     Calgary          B3  YYC-YLW  2024-2025            340700
8     Calgary          B3   yycyxx  2024-2025            340700
9    Edmonton          B1  yeg-yvr  2024-2025            258800

In [ ]:
# gates.info()
# gates.shape
# gates.isna().sum()
# gates.duplicated().sum()

         City Gate_Number Route_ID       Year  Annual_Gate_Cost
0  Abbotsford          G1  yxx-yyc  2024-2025            166800
1     Calgary          B1   YYCYVR  2024-2025            373200
2     Calgary          B1   yycyyz  2024-2025            373200
3     Calgary          B1   YYCYEG  2024-2025            373200
4     Calgary          B2  yyc-ywg  2024-2025            351900

In [56]:
gates[gates["Route_ID"].isna()]

       City Gate_Number Route_ID       Year  Annual_Gate_Cost
16  Halifax          A3      NaN  2024-2025            220700
28   Ottawa          A2      NaN  2024-2025            205000
72  Halifax          A3      NaN  2025-2026            225200
84   Ottawa          A2      NaN  2025-2026            208300

## Transactions

In [65]:
transactions.head(10)

,Transaction_ID,Booking_ID,Transaction_Date,Route_ID,Transaction_Type,Membership_Tier,Booking_Channel,Payment_Method,Amount
0,TX1525667,BK396819,2026-07-23 18:18,YYZYHZ,Ticket,Non-Member,Direct Web,Credit Card,954.80
1,TX1420893,BK245942,2026-03-14 05:23,yvr-yeg,Ticket,Blue,Corporate Portal,Credit Card,971.17
2,TX1313706,BK274024,2025-10-29 11:54,yvryeg,Food & Onboard,Non-Member,Online Travel Agency,Credit Card,9.87
3,TX1169582,BK374084,2025-04-30 02:50,YYT-YHZ,Ticket,Silver,Direct Web,Credit Card,744.61
4,TX1378465,BK319834,01/20/2026 04:02,YYZYYC,Ticket,Blue,Direct Web,Credit Card,1380.38
5,TX1133037,BK382994,2025-03-11 20:20,YQBYUL,Extra Baggage,Blue,Direct Web,Credit Card,45.06
6,TX1112418,BK332533,2025-02-12 10:58,YHZ-YYZ,Change Fee,Blue,Direct Web,Points + Cash,75.00
7,TX1363471,BK329720,2026-01-01 01:29,YWG-YYC,TICKET,Non-Member,Corporate Portal,Credit Card,1231.75
8,TX1413482,BK440357,2026-03-04 18:04,YYC-YVR,Ticket,Blue,Mobile App,Credit Card,837.35
9,TX1056794,BK321270,2024-11-28 02:15,YLW-YVR,Ticket,Non-Member,Mobile App,Debit,599.02

In [ ]:
# transactions.info()
# transactions.shape
# transactions.isna().sum()
transactions["Transaction_ID"].duplicated().sum()
# transactions["Transaction_ID"].duplicated(keep = False).sum()
# transactions.duplicated().sum()

np.int64(1856)

919 rows are exactly the same, 1856 rows have the same transaction ID

In [44]:
transactions[transactions["Transaction_ID"].duplicated(keep = False)].sort_values(by = "Transaction_ID").head(10)

,Transaction_ID,Booking_ID,Transaction_Date,Route_ID,Transaction_Type,Membership_Tier,Booking_Channel,Payment_Method,Amount
391057,TX1000138,BK188785,2024-09-01 05:39,yxeyyc,Ticket,Non-Member,Mobile App,points + cash,708.58
50092,TX1000138,BK188785,2024-09-01 05:39,yxeyyc,Ticket,Non-Member,Mobile App,POINTS + CASH,708.58
107840,TX1000200,BK247854,09/01/2024 08:06,YHZYUL,Ticket,Non-Member,Corporate Portal,Points + Cash,1019.00
18883,TX1000200,BK247854,09/01/2024 08:06,YHZYUL,Ticket,Non-Member,Corporate Portal,Points + Cash,1019.00
243826,TX1001267,BK146372,2024-09-03 10:44,yhz-yyz,Ticket,Non-Member,Website,Travel Voucher,1256.40
442476,TX1001267,BK146372,2024-09-03 10:44,yhz-yyz,Ticket,Non-Member,Website,Travel Voucher,1256.40
28478,TX1002597,BK418396,2024-09-06 01:19,YYC-YYZ,Ticket,Blue,Direct Web,Credit Card,1402.03
301935,TX1002597,BK418396,2024-09-06 01:19,YYC-YYZ,Ticket,Blue,Direct Web,credit card,1402.03
4546,TX1003061,BK194363,2024-09-06 18:31,ylw-yvr,Ticket,Non-Member,Mobile App,Credit Card,490.43
56702,TX1003061,BK194363,2024-09-06 18:31,ylw-yvr,Ticket,Non-Member,Mobile App,Credit Card,490.43