# Financial Analysis

In [109]:
# imports
import pandas as pd
import altair as alt
import matplotlib.pyplot as plt
import numpy as np

In [110]:
# loading data
gates = pd.read_csv("../data/processed/gates_clean.csv")

In [111]:
flight_costs = pd.read_csv("../data/processed/flight_costs_df.csv")

In [112]:
bookings = pd.read_csv("../data/processed/bookings.csv")

In [113]:
bookings_routes = pd.read_csv("../data/processed/booking_routes.csv")

In [114]:
gates.head(5)

         City Gate_Number Route_ID       Year  Annual_Gate_Cost
0  Abbotsford          G1  YXX-YYC  2024-2025            166800
1     Calgary          B1  YYC-YVR  2024-2025            373200
2     Calgary          B1  YYC-YYZ  2024-2025            373200
3     Calgary          B1  YYC-YEG  2024-2025            373200
4     Calgary          B2  YYC-YWG  2024-2025            351900

In [115]:
flight_costs.head(5)

,Cost_Date,Route_ID,From,To,Crew,Food,Fuel,Maintenance,Total
0,2024-09-01 06:30:00,YVR-YLW,Vancouver,Kelowna,1388.53,170.52,1401.75,1657.45,4618.25
1,2024-09-01 06:35:00,YLW-YYC,Kelowna,Calgary,1673.28,221.60,1800.44,1898.61,5593.93
2,2024-09-01 06:45:00,YYZ-YYC,Toronto,Calgary,12105.73,2037.11,16016.15,9391.66,39550.65
3,2024-09-01 06:50:00,YLW-YVR,Kelowna,Vancouver,1458.14,187.03,1532.94,1540.96,4719.07
4,2024-09-01 06:50:00,YQR-YYC,Regina,Calgary,2745.73,333.72,2923.61,2504.61,8507.67

In [116]:
bookings.head(9)

,Booking_ID,Change Fee,Extra Baggage,Food & Onboard,Refund,Seat Upgrade,Ticket,Total
0,BK100000,0.0,0.0,0.00,0.0,0.0,683.89,683.89
1,BK100001,0.0,0.0,27.81,0.0,0.0,558.37,586.18
2,BK100002,0.0,0.0,0.00,0.0,0.0,796.89,796.89
3,BK100003,0.0,0.0,0.00,0.0,0.0,596.12,596.12
4,BK100004,0.0,0.0,0.00,0.0,0.0,743.32,743.32
5,BK100005,0.0,0.0,0.00,0.0,0.0,1395.40,1395.40
6,BK100006,0.0,0.0,0.00,0.0,0.0,1339.30,1339.30
7,BK100007,0.0,0.0,0.00,0.0,0.0,865.09,865.09
8,BK100008,0.0,0.0,0.00,0.0,0.0,562.55,562.55

In [117]:
bookings_routes[bookings_routes["Booking_ID"].duplicated(keep = False)]

,Booking_ID,Route_ID,Change Fee,Extra Baggage,Food & Onboard,Refund,Seat Upgrade,Ticket,Total
6,BK100006,YWG-YYC,0.0,0.0,0.00,0.0,0.0,824.53,824.53
7,BK100006,YYC-YVR,0.0,0.0,0.00,0.0,0.0,514.77,514.77
11,BK100010,YVR-YYC,0.0,0.0,0.00,0.0,0.0,834.79,834.79
12,BK100010,YYC-YWG,0.0,0.0,0.00,0.0,0.0,1107.79,1107.79
39,BK100037,YVR-YYZ,0.0,0.0,7.23,0.0,0.0,1811.96,1819.19
...,...,...,...,...,...,...,...,...,...
365828,BK452918,YVR-YEG,0.0,0.0,0.00,0.0,0.0,701.46,701.46
365860,BK452950,YVR-YYZ,0.0,0.0,0.00,0.0,0.0,1488.88,1488.88
365861,BK452950,YYZ-YHZ,0.0,0.0,0.00,0.0,0.0,752.51,752.51
365903,BK452992,YVR-YYZ,0.0,0.0,0.00,0.0,0.0,1545.27,1545.27
365904,BK452992,YYZ-YHZ,0.0,0.0,26.00,0.0,0.0,741.80,767.80

## Fiscal Year 2024-2025

### Firm Costs

#### Gates

In [118]:
gates_2425 = gates[gates["Year"] == "2024-2025"]["Annual_Gate_Cost"].sum().round(2)
print(f"NorthByte spent ${gates_2425} for leasing gates in 2024-2025")

NorthByte spent $17423300 for leasing gates in 2024-2025

#### Flights

In [119]:
flight_costs.dtypes

Cost_Date          str
Route_ID           str
From               str
To                 str
Crew           float64
Food           float64
Fuel           float64
Maintenance    float64
Total          float64
dtype: object

In [120]:
flights_2425 = flight_costs[flight_costs["Cost_Date"].str.startswith("2024")]
flights_2425_total_costs = flights_2425["Total"].sum().round(2)
flights_2425_total_crew = flights_2425["Crew"].sum().round(2)
flights_2425_total_fuel = flights_2425["Fuel"].sum().round(2)
flights_2425_total_food = flights_2425["Food"].sum().round(2)
flights_2425_total_maintenance = flights_2425["Maintenance"].sum().round(2)

print(f"Total costs for 2024-2025 were: ${flights_2425_total_costs}")
print(f"Total crew costs for 2024-2025 were: ${flights_2425_total_crew}")
print(f"Total fuel costs for 2024-2025 were: ${flights_2425_total_fuel}")
print(f"Total food costs for 2024-2025 were: ${flights_2425_total_food}")
print(f"Total maintenance costs for 2024-2025 were: ${flights_2425_total_maintenance}")

Total costs for 2024-2025 were: $50358888.08
Total crew costs for 2024-2025 were: $15659961.02
Total fuel costs for 2024-2025 were: $17409937.38
Total food costs for 2024-2025 were: $2102429.14
Total maintenance costs for 2024-2025 were: $15186560.54

#### All Costs

In [ ]:
total_costs_2425 = gates_2425 + flights_2425_total_costs + flights_2425_total_crew + flights_2425_total_fuel + flights_2425_total_food + flights_2425_total_maintenance
print(f"Total costs for the fiscal year 2024-2025: ${total_costs_2425}")

Total costs for the fiscal year 2024-2025: $118141076.16

### Firm Revenue

## Fiscal Year 2025-2026

### Firm Costs

#### Gates

In [122]:
gates_2526 = gates[gates["Year"] == "2025-2026"]["Annual_Gate_Cost"].sum().round(2)
print(f"NorthByte spent ${gates_2526} for leasing gates in 2025-2026")

NorthByte spent $17819600 for leasing gates in 2025-2026

#### Flights

In [123]:
flights_2526 = flight_costs[flight_costs["Cost_Date"].str.startswith("2025")]
flights_2526_total_costs = flights_2526["Total"].sum().round(2)
flights_2526_total_crew = flights_2526["Crew"].sum().round(2)
flights_2526_total_fuel = flights_2526["Fuel"].sum().round(2)
flights_2526_total_food = flights_2526["Food"].sum().round(2)
flights_2526_total_maintenance = flights_2526["Maintenance"].sum().round(2)

print(f"Total costs for 2024-2025 were: ${flights_2526_total_costs}")
print(f"Total crew costs for 2024-2025 were: ${flights_2526_total_crew}")
print(f"Total fuel costs for 2024-2025 were: ${flights_2526_total_fuel}")
print(f"Total food costs for 2024-2025 were: ${flights_2526_total_food}")
print(f"Total maintenance costs for 2024-2025 were: ${flights_2526_total_maintenance}")

Total costs for 2024-2025 were: $220206517.87
Total crew costs for 2024-2025 were: $68409493.33
Total fuel costs for 2024-2025 were: $76503818.91
Total food costs for 2024-2025 were: $8660437.46
Total maintenance costs for 2024-2025 were: $66632768.17

#### All Costs

In [ ]:
total_costs_2526 = gates_2526 + flights_2526_total_costs + flights_2526_total_crew + flights_2526_total_fuel + flights_2526_total_food + flights_2526_total_maintenance
print(f"Total costs for the fiscal year 2025-2026: ${total_costs_2526}")

Total costs for the fiscal year 2025-2026: $458232635.74

### Firm Revenue

## Changes from 2024-2025 to 2025-2026

### Firm Costs

#### Gates

In [134]:
print(f"NorthByte increased spending on gates by: ${gates_2526 - gates_2425}")

print(f"Increasing their spending by on gates by: {(((gates_2526 - gates_2425)/gates_2425) * 100).round(2)}%")

NorthByte increased spending on gates by: $396300
Increasing their spending by on gates by: 2.27%

#### Flights

In [137]:
# flights
print(f"NorthByte increased spending on flights by: ${(flights_2526_total_costs - flights_2425_total_costs).round(2)}")
print(f"Increasing their spending by on flights by: {(((flights_2526_total_costs - flights_2425_total_costs)/flights_2425_total_costs) * 100).round(2)}%")

# crew
print(f"NorthByte increased spending on crew by: ${(flights_2526_total_crew - flights_2425_total_crew).round(2)}")
print(f"Increasing their spending by on crew by: {(((flights_2526_total_crew - flights_2425_total_crew)/flights_2425_total_crew) * 100).round(2)}%")
# fuel
print(f"NorthByte increased spending on fuel by: ${(flights_2526_total_fuel - flights_2425_total_fuel).round(2)}")
print(f"Increasing their spending by on fuel by: {(((flights_2526_total_fuel - flights_2425_total_fuel)/flights_2425_total_fuel) * 100).round(2)}%")
# food
print(f"NorthByte increased spending on food by: ${(flights_2526_total_food - flights_2425_total_food).round(2)}")
print(f"Increasing their spending by on food by: {(((flights_2526_total_food - flights_2425_total_food)/flights_2425_total_food) * 100).round(2)}%")
# maintenance
print(f"NorthByte increased spending on maintenance by: ${(flights_2526_total_maintenance - flights_2425_total_maintenance).round(2)}")
print(f"Increasing their spending by on maintenance by: {(((flights_2526_total_maintenance - flights_2425_total_maintenance)/flights_2425_total_maintenance) * 100).round(2)}%")

NorthByte increased spending on flights by: $169847629.79
Increasing their spending by on flights by: 337.27%
NorthByte increased spending on crew by: $52749532.31
Increasing their spending by on crew by: 336.84%
NorthByte increased spending on fuel by: $59093881.53
Increasing their spending by on fuel by: 339.43%
NorthByte increased spending on food by: $6558008.32
Increasing their spending by on food by: 311.93%
NorthByte increased spending on maintenance by: $51446207.63
Increasing their spending by on maintenance by: 338.76%

#### All Costs

In [144]:
print(f"Costs for the fiscal year 2024-2025 to 2025-2026 increased by a total of: ${(total_costs_2526 - total_costs_2425).round(2)}")
print(f"Increasing by: {(((total_costs_2526 - total_costs_2425)/total_costs_2425)*100).round(2)}%")

Costs for the fiscal year 2024-2025 to 2025-2026 increased by a total of: $340091559.58
Increasing by: 287.87%

### Firm Revenue