# Financial Analysis

In [29]:
# imports
import pandas as pd
import altair as alt
import matplotlib.pyplot as plt

In [30]:
# loading data
gates = pd.read_csv("../data/processed/gates_clean.csv")

In [31]:
gates = pd.read_csv("../data/processed/gates_clean.csv")

In [32]:
bookings = pd.read_csv("../data/processed/bookings.csv")

In [33]:
bookings_routes = pd.read_csv("../data/processed/booking_routes.csv")

In [34]:
gates.head(5)

         City Gate_Number Route_ID       Year  Annual_Gate_Cost
0  Abbotsford          G1  YXX-YYC  2024-2025            166800
1     Calgary          B1  YYC-YVR  2024-2025            373200
2     Calgary          B1  YYC-YYZ  2024-2025            373200
3     Calgary          B1  YYC-YEG  2024-2025            373200
4     Calgary          B2  YYC-YWG  2024-2025            351900

In [35]:
costs.head(5)

,Cost_Date,Route_ID,From,To,Crew,Food,Fuel,Maintenance,Total
0,2024-09-01 06:30:00,YVR-YLW,Vancouver,Kelowna,1388.53,170.52,1401.75,1657.45,4618.25
1,2024-09-01 06:35:00,YLW-YYC,Kelowna,Calgary,1673.28,221.60,1800.44,1898.61,5593.93
2,2024-09-01 06:45:00,YYZ-YYC,Toronto,Calgary,12105.73,2037.11,16016.15,9391.66,39550.65
3,2024-09-01 06:50:00,YLW-YVR,Kelowna,Vancouver,1458.14,187.03,1532.94,1540.96,4719.07
4,2024-09-01 06:50:00,YQR-YYC,Regina,Calgary,2745.73,333.72,2923.61,2504.61,8507.67

In [36]:
bookings.head(9)

,Booking_ID,Change Fee,Extra Baggage,Food & Onboard,Refund,Seat Upgrade,Ticket,Total
0,BK100000,0.0,0.0,0.00,0.0,0.0,683.89,683.89
1,BK100001,0.0,0.0,27.81,0.0,0.0,558.37,586.18
2,BK100002,0.0,0.0,0.00,0.0,0.0,796.89,796.89
3,BK100003,0.0,0.0,0.00,0.0,0.0,596.12,596.12
4,BK100004,0.0,0.0,0.00,0.0,0.0,743.32,743.32
5,BK100005,0.0,0.0,0.00,0.0,0.0,1395.40,1395.40
6,BK100006,0.0,0.0,0.00,0.0,0.0,1339.30,1339.30
7,BK100007,0.0,0.0,0.00,0.0,0.0,865.09,865.09
8,BK100008,0.0,0.0,0.00,0.0,0.0,562.55,562.55

In [37]:
bookings_routes[bookings_routes["Booking_ID"].duplicated(keep = False)]

,Booking_ID,Route_ID,Change Fee,Extra Baggage,Food & Onboard,Refund,Seat Upgrade,Ticket,Total
6,BK100006,YWG-YYC,0.0,0.0,0.00,0.0,0.0,824.53,824.53
7,BK100006,YYC-YVR,0.0,0.0,0.00,0.0,0.0,514.77,514.77
11,BK100010,YVR-YYC,0.0,0.0,0.00,0.0,0.0,834.79,834.79
12,BK100010,YYC-YWG,0.0,0.0,0.00,0.0,0.0,1107.79,1107.79
39,BK100037,YVR-YYZ,0.0,0.0,7.23,0.0,0.0,1811.96,1819.19
...,...,...,...,...,...,...,...,...,...
365828,BK452918,YVR-YEG,0.0,0.0,0.00,0.0,0.0,701.46,701.46
365860,BK452950,YVR-YYZ,0.0,0.0,0.00,0.0,0.0,1488.88,1488.88
365861,BK452950,YYZ-YHZ,0.0,0.0,0.00,0.0,0.0,752.51,752.51
365903,BK452992,YVR-YYZ,0.0,0.0,0.00,0.0,0.0,1545.27,1545.27
365904,BK452992,YYZ-YHZ,0.0,0.0,26.00,0.0,0.0,741.80,767.80

## Fiscal Year 2024-2025